"""Scan configured notes and regenerate INDEX.md from metadata comments."""

from __future__ import annotations

import json
import re
import sys
from datetime import date as Date
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
NOTES_ROOT = ROOT / "notes"
CONFIG_FILE = ROOT / "config" / "church-notes.json"
INDEX_FILE = ROOT / "INDEX.md"
METADATA_RE = re.compile(r"^<!--.*?-->", re.DOTALL)


def parse_metadata(text: str) -> dict[str, str]:
    match = METADATA_RE.match(text)
    if not match:
        return {}
    inner = match.group(0)[4:-3].strip()
    result: dict[str, str] = {}
    for part in inner.split("|"):
        if ":" in part:
            key, _, value = part.partition(":")
            result[key.strip()] = value.strip()
    return result


def load_config() -> dict:
    if not CONFIG_FILE.exists():
        return {"system_title": "Church Notes", "authors": []}
    return json.loads(CONFIG_FILE.read_text(encoding="utf-8"))


def collect_entries() -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    if not NOTES_ROOT.exists():
        return entries

    for md_file in sorted(NOTES_ROOT.rglob("*.md")):
        if md_file.name.startswith("."):
            continue
        metadata = parse_metadata(md_file.read_text(encoding="utf-8"))
        if not metadata:
            continue
        relative = md_file.relative_to(ROOT).as_posix()
        entries.append(
            {
                "date": metadata.get("date", "—"),
                "title": metadata.get("title") or md_file.stem,
                "type": metadata.get("type", "—"),
                "author": metadata.get("author", "—"),
                "speaker": metadata.get("speaker") or "—",
                "tags": metadata.get("tags") or "—",
                "summary": metadata.get("summary") or "—",
                "path": relative,
            }
        )
    entries.sort(key=lambda entry: (entry["date"], entry["author"], entry["type"]))
    return entries


def md_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_index(entries: list[dict[str, str]], config: dict) -> str:
    lines = [
        f"# {config.get('system_title', 'Church Notes')} — Index",
        "",
        f"_Auto-generated by `tools/build-index.py` — last updated {Date.today().isoformat()}._",
        "_Updated automatically by GitHub Actions when notes are committed._",
        "",
    ]

    if not entries:
        lines.extend(["No notes have been indexed yet.", ""])
        return "\n".join(lines)

    authors: dict[str, list[dict[str, str]]] = {}
    for entry in entries:
        authors.setdefault(entry["author"], []).append(entry)

    type_labels = {
        "service": "Church Services",
        "devotional": "Devotionals",
        "personal": "Personal / Ministry Notes",
    }

    for author, author_entries in authors.items():
        lines.extend([f"## {author}", ""])
        by_type: dict[str, list[dict[str, str]]] = {}
        for entry in author_entries:
            by_type.setdefault(entry["type"], []).append(entry)

        for entry_type in ("service", "devotional", "personal"):
            group = by_type.get(entry_type)
            if not group:
                continue
            lines.extend([f"### {type_labels[entry_type]}", ""])
            lines.append("| Date | Title | Speaker | Tags | Summary |")
            lines.append("|------|-------|---------|------|---------|")
            for entry in group:
                link = quote(entry["path"], safe="/().-_")
                title = f"[{md_escape(entry['title'])}]({link})"
                lines.append(
                    f"| {md_escape(entry['date'])} | {title} | {md_escape(entry['speaker'])} | "
                    f"{md_escape(entry['tags'])} | {md_escape(entry['summary'])} |"
                )
            lines.append("")

    return "\n".join(lines)


def main() -> None:
    if not NOTES_ROOT.exists():
        sys.exit("ERROR: notes directory not found. Run from the repository root.")
    config = load_config()
    entries = collect_entries()
    INDEX_FILE.write_text(render_index(entries, config), encoding="utf-8")
    print(f"INDEX.md written — {len(entries)} entries indexed.")


if __name__ == "__main__":
    main()
